name: CI/CD for VS Code Extension

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build extension
      run: npm run build

    - name: Run tests with VS Code environment
      uses: gabrielbb/xvfb-action@v1
      with:
        run: |
          # 安装 VS Code 测试运行器
          npm install -g @vscode/test-electron
          # 运行测试
          npx @vscode/test-electron --extensionDevelopmentPath=. --extensionTestsPath=dist/test

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.node-version }}
        path: |
          test-results/
          coverage/

  package:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build extension
      run: npm run build

    - name: Install VSCE
      run: npm install -g @vscode/vsce

    - name: Package extension
      run: vsce package

    - name: Upload extension package
      uses: actions/upload-artifact@v4
      with:
        name: starsfall-servers-manager
        path: '*.vsix'

  publish:
    runs-on: ubuntu-latest
    needs: package
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
    - name: Download extension package
      uses: actions/download-artifact@v4
      with:
        name: starsfall-servers-manager
        path: .

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install VSCE
      run: npm install -g @vscode/vsce

    - name: Publish to Marketplace
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
      run: |
        vsix_file=$(ls *.vsix | head -n 1)
        vsce publish -p $VSCE_PAT --packagePath $vsix_file